server:
  port: 8200
spring:
  application:
    name: mocroservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true